name: Kemenu Dark CI

on: [push]

jobs:

  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Test backend
        run: mvn -B clean test -pl :kemenu-admin-backend