name: Minimal Example CI

on: [push]

jobs:

  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set up Node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Test frontend
        run: |
          npm install frontend-client --prefix ./frontend-client
          npm --prefix frontend-client run test:unit
      - name: Test backend
        run: mvn -B clean test -pl :backend-server